package com.sf.jfinal.qs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmOrder<M extends BaseCrmOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	public java.lang.String getNumber() {
		return get("number");
	}

	public void setOrderType(java.lang.String orderType) {
		set("order_type", orderType);
	}

	public java.lang.String getOrderType() {
		return get("order_type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setRepairTime(java.util.Date repairTime) {
		set("repair_time", repairTime);
	}

	public java.util.Date getRepairTime() {
		return get("repair_time");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setApplianceBrand(java.lang.String applianceBrand) {
		set("appliance_brand", applianceBrand);
	}

	public java.lang.String getApplianceBrand() {
		return get("appliance_brand");
	}

	public void setApplianceCategory(java.lang.String applianceCategory) {
		set("appliance_category", applianceCategory);
	}

	public java.lang.String getApplianceCategory() {
		return get("appliance_category");
	}

	public void setApplianceModel(java.lang.String applianceModel) {
		set("appliance_model", applianceModel);
	}

	public java.lang.String getApplianceModel() {
		return get("appliance_model");
	}

	public void setApplianceBarcode(java.lang.String applianceBarcode) {
		set("appliance_barcode", applianceBarcode);
	}

	public java.lang.String getApplianceBarcode() {
		return get("appliance_barcode");
	}

	public void setApplianceBuyTime(java.util.Date applianceBuyTime) {
		set("appliance_buy_time", applianceBuyTime);
	}

	public java.util.Date getApplianceBuyTime() {
		return get("appliance_buy_time");
	}

	public void setApplianceNum(java.lang.Integer applianceNum) {
		set("appliance_num", applianceNum);
	}

	public java.lang.Integer getApplianceNum() {
		return get("appliance_num");
	}

	public void setApplianceMachineCode(java.lang.String applianceMachineCode) {
		set("appliance_machine_code", applianceMachineCode);
	}

	public java.lang.String getApplianceMachineCode() {
		return get("appliance_machine_code");
	}

	public void setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
	}

	public java.lang.String getCustomerName() {
		return get("customer_name");
	}

	public void setCustomerAddress(java.lang.String customerAddress) {
		set("customer_address", customerAddress);
	}

	public java.lang.String getCustomerAddress() {
		return get("customer_address");
	}

	public void setCustomerMobile(java.lang.String customerMobile) {
		set("customer_mobile", customerMobile);
	}

	public java.lang.String getCustomerMobile() {
		return get("customer_mobile");
	}

	public void setCustomerTelephone(java.lang.String customerTelephone) {
		set("customer_telephone", customerTelephone);
	}

	public java.lang.String getCustomerTelephone() {
		return get("customer_telephone");
	}

	public void setCustomerTelephone2(java.lang.String customerTelephone2) {
		set("customer_telephone2", customerTelephone2);
	}

	public java.lang.String getCustomerTelephone2() {
		return get("customer_telephone2");
	}

	public void setCustomerLnglat(java.lang.String customerLnglat) {
		set("customer_lnglat", customerLnglat);
	}

	public java.lang.String getCustomerLnglat() {
		return get("customer_lnglat");
	}

	public void setPromiseTime(java.util.Date promiseTime) {
		set("promise_time", promiseTime);
	}

	public java.util.Date getPromiseTime() {
		return get("promise_time");
	}

	public void setPromiseLimit(java.lang.String promiseLimit) {
		set("promise_limit", promiseLimit);
	}

	public java.lang.String getPromiseLimit() {
		return get("promise_limit");
	}

	public void setCustomerFeedback(java.lang.String customerFeedback) {
		set("customer_feedback", customerFeedback);
	}

	public java.lang.String getCustomerFeedback() {
		return get("customer_feedback");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setOrigin(java.lang.String origin) {
		set("origin", origin);
	}

	public java.lang.String getOrigin() {
		return get("origin");
	}

	public void setServiceType(java.lang.String serviceType) {
		set("service_type", serviceType);
	}

	public java.lang.String getServiceType() {
		return get("service_type");
	}

	public void setLevel(java.lang.String level) {
		set("level", level);
	}

	public java.lang.String getLevel() {
		return get("level");
	}

	public void setSiteName(java.lang.String siteName) {
		set("site_name", siteName);
	}

	public java.lang.String getSiteName() {
		return get("site_name");
	}

	public void setEmployeId(java.lang.String employeId) {
		set("employe_id", employeId);
	}

	public java.lang.String getEmployeId() {
		return get("employe_id");
	}

	public void setEmployeName(java.lang.String employeName) {
		set("employe_name", employeName);
	}

	public java.lang.String getEmployeName() {
		return get("employe_name");
	}

	public void setMessengerId(java.lang.String messengerId) {
		set("messenger_id", messengerId);
	}

	public java.lang.String getMessengerId() {
		return get("messenger_id");
	}

	public void setMessengerName(java.lang.String messengerName) {
		set("messenger_name", messengerName);
	}

	public java.lang.String getMessengerName() {
		return get("messenger_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateName(java.lang.String updateName) {
		set("update_name", updateName);
	}

	public java.lang.String getUpdateName() {
		return get("update_name");
	}

	public void setWarrantyType(java.lang.String warrantyType) {
		set("warranty_type", warrantyType);
	}

	public java.lang.String getWarrantyType() {
		return get("warranty_type");
	}

	public void setServiceMode(java.lang.String serviceMode) {
		set("service_mode", serviceMode);
	}

	public java.lang.String getServiceMode() {
		return get("service_mode");
	}

	public void setMalfunctionType(java.lang.String malfunctionType) {
		set("malfunction_type", malfunctionType);
	}

	public java.lang.String getMalfunctionType() {
		return get("malfunction_type");
	}

	public void setMalfunctionDescription(java.lang.String malfunctionDescription) {
		set("malfunction_description", malfunctionDescription);
	}

	public java.lang.String getMalfunctionDescription() {
		return get("malfunction_description");
	}

	public void setMalfunctionCause(java.lang.String malfunctionCause) {
		set("malfunction_cause", malfunctionCause);
	}

	public java.lang.String getMalfunctionCause() {
		return get("malfunction_cause");
	}

	public void setMalfunctionCauseDescription(java.lang.String malfunctionCauseDescription) {
		set("malfunction_cause_description", malfunctionCauseDescription);
	}

	public java.lang.String getMalfunctionCauseDescription() {
		return get("malfunction_cause_description");
	}

	public void setMeasures(java.lang.String measures) {
		set("measures", measures);
	}

	public java.lang.String getMeasures() {
		return get("measures");
	}

	public void setMeasuresDescription(java.lang.String measuresDescription) {
		set("measures_description", measuresDescription);
	}

	public java.lang.String getMeasuresDescription() {
		return get("measures_description");
	}

	public void setSiteId(java.lang.String siteId) {
		set("site_id", siteId);
	}

	public java.lang.String getSiteId() {
		return get("site_id");
	}

	public void setLatestProcess(java.lang.String latestProcess) {
		set("latest_process", latestProcess);
	}

	public java.lang.String getLatestProcess() {
		return get("latest_process");
	}

	public void setLatestProcessTime(java.util.Date latestProcessTime) {
		set("latest_process_time", latestProcessTime);
	}

	public java.util.Date getLatestProcessTime() {
		return get("latest_process_time");
	}

	public void setProcessDetail(java.lang.String processDetail) {
		set("process_detail", processDetail);
	}

	public java.lang.String getProcessDetail() {
		return get("process_detail");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCanoper(java.lang.String canoper) {
		set("canoper", canoper);
	}

	public java.lang.String getCanoper() {
		return get("canoper");
	}

	public void setDropinCount(java.lang.Integer dropinCount) {
		set("dropin_count", dropinCount);
	}

	public java.lang.Integer getDropinCount() {
		return get("dropin_count");
	}

	public void setRejectCount(java.lang.Integer rejectCount) {
		set("reject_count", rejectCount);
	}

	public java.lang.Integer getRejectCount() {
		return get("reject_count");
	}

	public void setTelCount(java.lang.Integer telCount) {
		set("tel_count", telCount);
	}

	public java.lang.Integer getTelCount() {
		return get("tel_count");
	}

	public void setReturnCard(java.lang.String returnCard) {
		set("return_card", returnCard);
	}

	public java.lang.String getReturnCard() {
		return get("return_card");
	}

	public void setReturnCardTime(java.util.Date returnCardTime) {
		set("return_card_time", returnCardTime);
	}

	public java.util.Date getReturnCardTime() {
		return get("return_card_time");
	}

	public void setWhetherCollection(java.lang.String whetherCollection) {
		set("whether_collection", whetherCollection);
	}

	public java.lang.String getWhetherCollection() {
		return get("whether_collection");
	}

	public void setFittingFlag(java.lang.String fittingFlag) {
		set("fitting_flag", fittingFlag);
	}

	public java.lang.String getFittingFlag() {
		return get("fitting_flag");
	}

	public void setServeCost(java.math.BigDecimal serveCost) {
		set("serve_cost", serveCost);
	}

	public java.math.BigDecimal getServeCost() {
		return get("serve_cost");
	}

	public void setAuxiliaryCost(java.math.BigDecimal auxiliaryCost) {
		set("auxiliary_cost", auxiliaryCost);
	}

	public java.math.BigDecimal getAuxiliaryCost() {
		return get("auxiliary_cost");
	}

	public void setWarrantyCost(java.math.BigDecimal warrantyCost) {
		set("warranty_cost", warrantyCost);
	}

	public java.math.BigDecimal getWarrantyCost() {
		return get("warranty_cost");
	}

	public void setConfirmCost(java.math.BigDecimal confirmCost) {
		set("confirm_cost", confirmCost);
	}

	public java.math.BigDecimal getConfirmCost() {
		return get("confirm_cost");
	}

	public void setCallbackResult(java.lang.String callbackResult) {
		set("callback_result", callbackResult);
	}

	public java.lang.String getCallbackResult() {
		return get("callback_result");
	}

	public void setCallbackTime(java.util.Date callbackTime) {
		set("callback_time", callbackTime);
	}

	public java.util.Date getCallbackTime() {
		return get("callback_time");
	}

	public void setReview(java.lang.String review) {
		set("review", review);
	}

	public java.lang.String getReview() {
		return get("review");
	}

	public void setReviewRemark(java.lang.String reviewRemark) {
		set("review_remark", reviewRemark);
	}

	public java.lang.String getReviewRemark() {
		return get("review_remark");
	}

	public void setReviewTime(java.util.Date reviewTime) {
		set("review_time", reviewTime);
	}

	public java.util.Date getReviewTime() {
		return get("review_time");
	}

	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}

	public java.lang.String getFlag() {
		return get("flag");
	}

	public void setFlagDesc(java.lang.String flagDesc) {
		set("flag_desc", flagDesc);
	}

	public java.lang.String getFlagDesc() {
		return get("flag_desc");
	}

	public void setFlagAlertDate(java.util.Date flagAlertDate) {
		set("flag_alert_date", flagAlertDate);
	}

	public java.util.Date getFlagAlertDate() {
		return get("flag_alert_date");
	}

	public void setRecordAccount(java.lang.String recordAccount) {
		set("record_account", recordAccount);
	}

	public java.lang.String getRecordAccount() {
		return get("record_account");
	}

	public void setBdImgs(java.lang.String bdImgs) {
		set("bd_imgs", bdImgs);
	}

	public java.lang.String getBdImgs() {
		return get("bd_imgs");
	}

	public void setRecordAccountTime(java.util.Date recordAccountTime) {
		set("record_account_time", recordAccountTime);
	}

	public java.util.Date getRecordAccountTime() {
		return get("record_account_time");
	}

	public void setCustomerSign(java.lang.String customerSign) {
		set("customer_sign", customerSign);
	}

	public java.lang.String getCustomerSign() {
		return get("customer_sign");
	}

	public void setFactoryNumber(java.lang.String factoryNumber) {
		set("factory_number", factoryNumber);
	}

	public java.lang.String getFactoryNumber() {
		return get("factory_number");
	}

	public void setPleaseReferMall(java.lang.String pleaseReferMall) {
		set("please_refer_mall", pleaseReferMall);
	}

	public java.lang.String getPleaseReferMall() {
		return get("please_refer_mall");
	}

	public void setParentDipatchFlag(java.lang.String parentDipatchFlag) {
		set("parent_dipatch_flag", parentDipatchFlag);
	}

	public java.lang.String getParentDipatchFlag() {
		return get("parent_dipatch_flag");
	}

	public void setParentSiteId(java.lang.String parentSiteId) {
		set("parent_site_id", parentSiteId);
	}

	public java.lang.String getParentSiteId() {
		return get("parent_site_id");
	}

	public void setParentStatus(java.lang.String parentStatus) {
		set("parent_status", parentStatus);
	}

	public java.lang.String getParentStatus() {
		return get("parent_status");
	}

	public void setSeq(java.lang.Integer seq) {
		set("seq", seq);
	}

	public java.lang.Integer getSeq() {
		return get("seq");
	}

	public void setOrderNo400(java.lang.String orderNo400) {
		set("order_no_400", orderNo400);
	}

	public java.lang.String getOrderNo400() {
		return get("order_no_400");
	}

	public void setPrintTimes(java.lang.Integer printTimes) {
		set("print_times", printTimes);
	}

	public java.lang.Integer getPrintTimes() {
		return get("print_times");
	}

}
