package com.sf.jfinal.qs.model.master.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmOrder<M extends BaseCrmOrder<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setNumber(String number) {
		set("number", number);
	}

	public String getNumber() {
		return get("number");
	}

	public void setOrderType(String orderType) {
		set("order_type", orderType);
	}

	public String getOrderType() {
		return get("order_type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setRepairTime(java.util.Date repairTime) {
		set("repair_time", repairTime);
	}

	public java.util.Date getRepairTime() {
		return get("repair_time");
	}

	public void setCreateBy(String createBy) {
		set("create_by", createBy);
	}

	public String getCreateBy() {
		return get("create_by");
	}

	public void setApplianceBrand(String applianceBrand) {
		set("appliance_brand", applianceBrand);
	}

	public String getApplianceBrand() {
		return get("appliance_brand");
	}

	public void setApplianceCategory(String applianceCategory) {
		set("appliance_category", applianceCategory);
	}

	public String getApplianceCategory() {
		return get("appliance_category");
	}

	public void setApplianceModel(String applianceModel) {
		set("appliance_model", applianceModel);
	}

	public String getApplianceModel() {
		return get("appliance_model");
	}

	public void setApplianceBarcode(String applianceBarcode) {
		set("appliance_barcode", applianceBarcode);
	}

	public String getApplianceBarcode() {
		return get("appliance_barcode");
	}

	public void setApplianceBuyTime(java.util.Date applianceBuyTime) {
		set("appliance_buy_time", applianceBuyTime);
	}

	public java.util.Date getApplianceBuyTime() {
		return get("appliance_buy_time");
	}

	public void setApplianceNum(Integer applianceNum) {
		set("appliance_num", applianceNum);
	}

	public Integer getApplianceNum() {
		return get("appliance_num");
	}

	public void setApplianceMachineCode(String applianceMachineCode) {
		set("appliance_machine_code", applianceMachineCode);
	}

	public String getApplianceMachineCode() {
		return get("appliance_machine_code");
	}

	public void setCustomerName(String customerName) {
		set("customer_name", customerName);
	}

	public String getCustomerName() {
		return get("customer_name");
	}

	public void setCustomerAddress(String customerAddress) {
		set("customer_address", customerAddress);
	}

	public String getCustomerAddress() {
		return get("customer_address");
	}

	public void setCustomerMobile(String customerMobile) {
		set("customer_mobile", customerMobile);
	}

	public String getCustomerMobile() {
		return get("customer_mobile");
	}

	public void setCustomerTelephone(String customerTelephone) {
		set("customer_telephone", customerTelephone);
	}

	public String getCustomerTelephone() {
		return get("customer_telephone");
	}

	public void setCustomerTelephone2(String customerTelephone2) {
		set("customer_telephone2", customerTelephone2);
	}

	public String getCustomerTelephone2() {
		return get("customer_telephone2");
	}

	public void setCustomerLnglat(String customerLnglat) {
		set("customer_lnglat", customerLnglat);
	}

	public String getCustomerLnglat() {
		return get("customer_lnglat");
	}

	public void setPromiseTime(java.util.Date promiseTime) {
		set("promise_time", promiseTime);
	}

	public java.util.Date getPromiseTime() {
		return get("promise_time");
	}

	public void setPromiseLimit(String promiseLimit) {
		set("promise_limit", promiseLimit);
	}

	public String getPromiseLimit() {
		return get("promise_limit");
	}

	public void setCustomerFeedback(String customerFeedback) {
		set("customer_feedback", customerFeedback);
	}

	public String getCustomerFeedback() {
		return get("customer_feedback");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return get("remarks");
	}

	public void setOrigin(String origin) {
		set("origin", origin);
	}

	public String getOrigin() {
		return get("origin");
	}

	public void setServiceType(String serviceType) {
		set("service_type", serviceType);
	}

	public String getServiceType() {
		return get("service_type");
	}

	public void setLevel(String level) {
		set("level", level);
	}

	public String getLevel() {
		return get("level");
	}

	public void setSiteName(String siteName) {
		set("site_name", siteName);
	}

	public String getSiteName() {
		return get("site_name");
	}

	public void setEmployeId(String employeId) {
		set("employe_id", employeId);
	}

	public String getEmployeId() {
		return get("employe_id");
	}

	public void setEmployeName(String employeName) {
		set("employe_name", employeName);
	}

	public String getEmployeName() {
		return get("employe_name");
	}

	public void setMessengerId(String messengerId) {
		set("messenger_id", messengerId);
	}

	public String getMessengerId() {
		return get("messenger_id");
	}

	public void setMessengerName(String messengerName) {
		set("messenger_name", messengerName);
	}

	public String getMessengerName() {
		return get("messenger_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateName(String updateName) {
		set("update_name", updateName);
	}

	public String getUpdateName() {
		return get("update_name");
	}

	public void setWarrantyType(String warrantyType) {
		set("warranty_type", warrantyType);
	}

	public String getWarrantyType() {
		return get("warranty_type");
	}

	public void setServiceMode(String serviceMode) {
		set("service_mode", serviceMode);
	}

	public String getServiceMode() {
		return get("service_mode");
	}

	public void setMalfunctionType(String malfunctionType) {
		set("malfunction_type", malfunctionType);
	}

	public String getMalfunctionType() {
		return get("malfunction_type");
	}

	public void setMalfunctionDescription(String malfunctionDescription) {
		set("malfunction_description", malfunctionDescription);
	}

	public String getMalfunctionDescription() {
		return get("malfunction_description");
	}

	public void setMalfunctionCause(String malfunctionCause) {
		set("malfunction_cause", malfunctionCause);
	}

	public String getMalfunctionCause() {
		return get("malfunction_cause");
	}

	public void setMalfunctionCauseDescription(String malfunctionCauseDescription) {
		set("malfunction_cause_description", malfunctionCauseDescription);
	}

	public String getMalfunctionCauseDescription() {
		return get("malfunction_cause_description");
	}

	public void setMeasures(String measures) {
		set("measures", measures);
	}

	public String getMeasures() {
		return get("measures");
	}

	public void setMeasuresDescription(String measuresDescription) {
		set("measures_description", measuresDescription);
	}

	public String getMeasuresDescription() {
		return get("measures_description");
	}

	public void setSiteId(String siteId) {
		set("site_id", siteId);
	}

	public String getSiteId() {
		return get("site_id");
	}

	public void setLatestProcess(String latestProcess) {
		set("latest_process", latestProcess);
	}

	public String getLatestProcess() {
		return get("latest_process");
	}

	public void setLatestProcessTime(java.util.Date latestProcessTime) {
		set("latest_process_time", latestProcessTime);
	}

	public java.util.Date getLatestProcessTime() {
		return get("latest_process_time");
	}

	public void setProcessDetail(String processDetail) {
		set("process_detail", processDetail);
	}

	public String getProcessDetail() {
		return get("process_detail");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return get("status");
	}

	public void setCanoper(String canoper) {
		set("canoper", canoper);
	}

	public String getCanoper() {
		return get("canoper");
	}

	public void setDropinCount(Integer dropinCount) {
		set("dropin_count", dropinCount);
	}

	public Integer getDropinCount() {
		return get("dropin_count");
	}

	public void setRejectCount(Integer rejectCount) {
		set("reject_count", rejectCount);
	}

	public Integer getRejectCount() {
		return get("reject_count");
	}

	public void setTelCount(Integer telCount) {
		set("tel_count", telCount);
	}

	public Integer getTelCount() {
		return get("tel_count");
	}

	public void setReturnCard(String returnCard) {
		set("return_card", returnCard);
	}

	public String getReturnCard() {
		return get("return_card");
	}

	public void setReturnCardTime(java.util.Date returnCardTime) {
		set("return_card_time", returnCardTime);
	}

	public java.util.Date getReturnCardTime() {
		return get("return_card_time");
	}

	public void setWhetherCollection(String whetherCollection) {
		set("whether_collection", whetherCollection);
	}

	public String getWhetherCollection() {
		return get("whether_collection");
	}

	public void setFittingFlag(String fittingFlag) {
		set("fitting_flag", fittingFlag);
	}

	public String getFittingFlag() {
		return get("fitting_flag");
	}

	public void setServeCost(java.math.BigDecimal serveCost) {
		set("serve_cost", serveCost);
	}

	public java.math.BigDecimal getServeCost() {
		return get("serve_cost");
	}

	public void setAuxiliaryCost(java.math.BigDecimal auxiliaryCost) {
		set("auxiliary_cost", auxiliaryCost);
	}

	public java.math.BigDecimal getAuxiliaryCost() {
		return get("auxiliary_cost");
	}

	public void setWarrantyCost(java.math.BigDecimal warrantyCost) {
		set("warranty_cost", warrantyCost);
	}

	public java.math.BigDecimal getWarrantyCost() {
		return get("warranty_cost");
	}

	public void setConfirmCost(java.math.BigDecimal confirmCost) {
		set("confirm_cost", confirmCost);
	}

	public java.math.BigDecimal getConfirmCost() {
		return get("confirm_cost");
	}

	public void setCallbackResult(String callbackResult) {
		set("callback_result", callbackResult);
	}

	public String getCallbackResult() {
		return get("callback_result");
	}

	public void setCallbackTime(java.util.Date callbackTime) {
		set("callback_time", callbackTime);
	}

	public java.util.Date getCallbackTime() {
		return get("callback_time");
	}

	public void setReview(String review) {
		set("review", review);
	}

	public String getReview() {
		return get("review");
	}

	public void setReviewRemark(String reviewRemark) {
		set("review_remark", reviewRemark);
	}

	public String getReviewRemark() {
		return get("review_remark");
	}

	public void setReviewTime(java.util.Date reviewTime) {
		set("review_time", reviewTime);
	}

	public java.util.Date getReviewTime() {
		return get("review_time");
	}

	public void setFlag(String flag) {
		set("flag", flag);
	}

	public String getFlag() {
		return get("flag");
	}

	public void setFlagDesc(String flagDesc) {
		set("flag_desc", flagDesc);
	}

	public String getFlagDesc() {
		return get("flag_desc");
	}

	public void setFlagAlertDate(java.util.Date flagAlertDate) {
		set("flag_alert_date", flagAlertDate);
	}

	public java.util.Date getFlagAlertDate() {
		return get("flag_alert_date");
	}

	public void setRecordAccount(String recordAccount) {
		set("record_account", recordAccount);
	}

	public String getRecordAccount() {
		return get("record_account");
	}

	public void setBdImgs(String bdImgs) {
		set("bd_imgs", bdImgs);
	}

	public String getBdImgs() {
		return get("bd_imgs");
	}

	public void setRecordAccountTime(java.util.Date recordAccountTime) {
		set("record_account_time", recordAccountTime);
	}

	public java.util.Date getRecordAccountTime() {
		return get("record_account_time");
	}

	public void setCustomerSign(String customerSign) {
		set("customer_sign", customerSign);
	}

	public String getCustomerSign() {
		return get("customer_sign");
	}

	public void setFactoryNumber(String factoryNumber) {
		set("factory_number", factoryNumber);
	}

	public String getFactoryNumber() {
		return get("factory_number");
	}

	public void setPleaseReferMall(String pleaseReferMall) {
		set("please_refer_mall", pleaseReferMall);
	}

	public String getPleaseReferMall() {
		return get("please_refer_mall");
	}

	public void setParentDipatchFlag(String parentDipatchFlag) {
		set("parent_dipatch_flag", parentDipatchFlag);
	}

	public String getParentDipatchFlag() {
		return get("parent_dipatch_flag");
	}

	public void setParentSiteId(String parentSiteId) {
		set("parent_site_id", parentSiteId);
	}

	public String getParentSiteId() {
		return get("parent_site_id");
	}

	public void setParentStatus(String parentStatus) {
		set("parent_status", parentStatus);
	}

	public String getParentStatus() {
		return get("parent_status");
	}

	public void setSeq(Integer seq) {
		set("seq", seq);
	}

	public Integer getSeq() {
		return get("seq");
	}

	public void setOrderNo400(String orderNo400) {
		set("order_no_400", orderNo400);
	}

	public String getOrderNo400() {
		return get("order_no_400");
	}

	public void setPrintTimes(Integer printTimes) {
		set("print_times", printTimes);
	}

	public Integer getPrintTimes() {
		return get("print_times");
	}

}
