package com.sf.jfinal.qs.model.master;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.sf.jfinal.qs.model.master.CrmOrder;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MasterMappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("crm_order", "id", CrmOrder.class);
	}
}

