package com.sf.jfinal.qs.model.master;

import com.sf.jfinal.qs.model.master.base.BaseCrmOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmOrder extends BaseCrmOrder<CrmOrder> {
	public static final CrmOrder dao = new CrmOrder();
}
