package com.sf.jfinal.qs.model.slave;

import com.sf.jfinal.qs.model.slave.base.BasePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public static final Person dao = new Person();
}
